app = "telegram-bot"

[build]

[env]
  PYTHONUNBUFFERED = "1"

# Сервис для бота (нужен для проверок здоровья)
[[services]]
  internal_port = 8080
  protocol = "tcp"
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 8080

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
